apponitment = input ("Enter your age ")
year = 90 - int(apponitment)
month = (90*12) - (int(apponitment) * 12)
week = (90*52) -  (int(apponitment) * 52)
print (f"your apponitment is after {year} years, {month} months, or {week} weeks") 